#!/usr/bin/env python3
"""
Stage a NAMED list of Codeforces problems for annotation.

scripts/fetch_codeforces.py samples a rating band. This one takes a curated list
— problems someone chose deliberately — and stages exactly those, in the same
cache format the annotator already reads.

Statements come from the public `open-r1/codeforces` dataset, because
codeforces.com is Cloudflare-blocked for scripts. That dataset is ~180 MB over
~9.5k paged rows and the read genuinely fails sometimes (a truncated response
killed an earlier run at 118/180 MB), so every page is retried and a page that
will not come back is reported rather than silently skipped.

The URL blocks are grouped by contest slot, which makes the slot the record's
`source_topic` for free — the annotator reads topics off "# A / B" headings.

  python3 scripts/fetch_codeforces_named.py --list data/div2_ladder.json
"""

from __future__ import annotations

import argparse
from cache_io import merge_json_map
import json
import sys
import time
from http.client import IncompleteRead
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "data" / "cache" / "codeforces_statements.json"
URLS = ROOT / "Problems" / "urls_codeforces.txt"
ROWS_URL = (
    "https://datasets-server.huggingface.co/rows"
    "?dataset=open-r1%2Fcodeforces&config=default&split=train&offset={offset}&length={length}"
)
MIN_STATEMENT = 80


def get_json(url: str, tries: int = 5) -> dict:
    last: Exception | None = None
    for attempt in range(tries):
        try:
            req = Request(url, headers={"user-agent": "cosine corpus builder"})
            with urlopen(req, timeout=90) as res:
                return json.loads(res.read().decode("utf8"))
        except (HTTPError, URLError, TimeoutError, IncompleteRead, ValueError) as exc:
            last = exc
            if attempt == tries - 1:
                break
            time.sleep(3 * (attempt + 1))
            print(f"  retry {attempt + 1}: {exc}", file=sys.stderr)
    raise RuntimeError(f"page failed after {tries} tries: {last}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", type=Path, required=True, help="JSON with a `problems` array of {id, slot}")
    ap.add_argument("--page", type=int, default=100)
    args = ap.parse_args()

    curated = json.loads(args.list.read_text())["problems"]
    want = {p["id"]: p for p in curated}
    print(f"looking for {len(want)} curated problems")

    first = get_json(ROWS_URL.format(offset=0, length=1))
    total = int(first.get("num_rows_total") or 0)
    print(f"dataset rows: {total}")

    found: dict[str, dict] = {}
    failed_pages: list[int] = []
    for offset in range(0, total, args.page):
        try:
            data = get_json(ROWS_URL.format(offset=offset, length=args.page))
        except RuntimeError as exc:
            failed_pages.append(offset)
            print(f"  page {offset} unreadable: {exc}", file=sys.stderr)
            continue
        for entry in data.get("rows", []):
            r = entry.get("row") or {}
            contest, index = r.get("contest_id"), (r.get("index") or "")
            if not contest or not index:
                continue
            pid = f"codeforces-{contest}-{str(index).lower()}"
            meta = want.get(pid)
            if not meta or pid in found:
                continue
            statement = (r.get("description") or "").strip()
            if len(statement) < MIN_STATEMENT:
                continue
            found[pid] = {
                "id": pid,
                "contest_id": contest,
                "index": index,
                "title": r.get("title") or meta.get("name") or f"{contest}{index}",
                "rating": r.get("rating") or meta.get("rating"),
                "tags": r.get("tags") or [],
                "statement": statement[:6000],
                "url": (f"https://codeforces.com/gym/{contest}/problem/{index}" if int(contest) >= 100000
                        else f"https://codeforces.com/problemset/problem/{contest}/{index}"),
                "slot": meta.get("slot"),
                "gap_tag": meta.get("gap_tag"),
            }
        if offset % (args.page * 20) == 0:
            print(f"  scanned {offset + args.page}/{total}, found {len(found)}/{len(want)}")

    merge_json_map(CACHE, found)

    lines = ["# Generated by scripts/fetch_codeforces_named.py; statements come from",
             "# data/cache/codeforces_statements.json, not codeforces.com.", ""]
    # Group by whatever the list carries. A curated list may group by contest
    # slot, a gap-fill list by the judge tag that selected it, and a plain list
    # by nothing at all — that last case used to write ZERO url blocks, so the
    # annotator was handed an empty file and reported "wrote 0 records".
    key = "slot" if any(p.get("slot") for p in found.values()) else "gap_tag"
    buckets = {}
    for p in found.values():
        buckets.setdefault(p.get(key) or "gap fill", []).append(p)
    for name, block in sorted(buckets.items()):
        pretty = str(name).replace("div2-", "Div 2 ").replace("-", " ").title()
        lines.append(f"# Codeforces / {pretty}")
        lines.extend(p["url"] for p in sorted(block, key=lambda p: p["id"]))
        lines.append("")
    URLS.write_text("\n".join(lines))

    absent = sorted(set(want) - set(found))
    print(f"\nstaged {len(found)}/{len(want)} -> {CACHE.relative_to(ROOT)}")
    if failed_pages:
        print(f"  {len(failed_pages)} page(s) unreadable — rerun to fill: {failed_pages[:10]}")
    if absent:
        print(f"  {len(absent)} not in the dataset (too recent, or no statement): {absent[:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
