#!/usr/bin/env python3
"""
Stage problems from a contest link.

    python3 scripts/ingest_contest.py https://leetcode.com/contest/weekly-contest-513/
    python3 scripts/ingest_contest.py https://codeforces.com/contest/2248
    python3 scripts/ingest_contest.py --retry-pending
    python3 scripts/ingest_contest.py --dry-run <url>

This only STAGES: it appends URLs to Problems/urls_contests.txt and, for
Codeforces, merges statements into the shared cache. Annotation, embedding and
validation stay separate commands, and nothing here ever commits — same
discipline as scripts/refresh_corpus.sh. The script prints the next steps.

WHY THE TWO JUDGES BEHAVE DIFFERENTLY

LeetCode works end to end the moment a contest ends: the GraphQL `contest`
query lists the problems and `question(titleSlug)` returns the full statement
and difficulty immediately. (The REST endpoint /contest/api/info/<slug>/ is
Cloudflare-403 to scripts — GraphQL is the way in.)

Codeforces cannot. codeforces.com is Cloudflare-blocked, so statements come
from the open-r1/codeforces HuggingFace dataset, which lags live contests by
a wide margin — contest 2248 is not in it, and fresh contests also report
`rating: null` for weeks. A problem with no statement is nearly unsearchable
(the statement is the bulk of the indexed document) and would dilute the
benchmark. So Codeforces problems that aren't in the dataset yet are QUEUED in
data/pending_contests.json and retried with --retry-pending, ingesting the week
their statement lands. Nothing is lost; nothing half-formed enters the corpus.

WHY --model gpt-4.1 FOR CONTESTS

The bulk pipeline runs gpt-4.1-mini, which is right for thousands of problems.
A contest is a dozen, and the intended technique is often invisible in the
statement: for "Minimum Possible Maximum Waiting Time" mini answered
binary-search-answer + greedy + simulation, where the real solution binary
searches the answer and checks feasibility with a memoised dp. gpt-4.1 found
the dp. Rewriting the prompt did not help — the model was the bottleneck — and
at contest volume the cost difference is noise.

WHY Q1 IS SKIPPED ON LEETCODE

A weekly/biweekly contest is four problems worth 3/4/5/6 points. Q1 (credit 3)
is the warm-up and is nearly always Easy, and this corpus is deliberately
hard-focused. `credit` is used rather than the difficulty label because it is
structural and available immediately, while the label can still move.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from update_problem_urls import LEETCODE_GRAPHQL_URL, request_json  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SEED_FILE = ROOT / "Problems" / "urls_contests.txt"
CF_STATEMENTS = ROOT / "data" / "cache" / "codeforces_statements.json"
PENDING = ROOT / "data" / "pending_contests.json"
HF_INDEX = ROOT / "data" / "cache" / "open_r1_index.json"
HF_INDEX_MAX_AGE_DAYS = 7
CORPUS = ROOT / "data" / "problemset_llm"
HF_ROWS = (
    "https://datasets-server.huggingface.co/rows"
    "?dataset=open-r1%2Fcodeforces&config=default&split=train&offset={offset}&length={length}"
)
CF_STANDINGS = "https://codeforces.com/api/contest.standings?contestId={cid}"
LC_SKIP_CREDIT = 3  # Q1

SEED_HEADER = [
    "# Generated by scripts/ingest_contest.py — one block per contest.",
    "# Consumed with: annotate_problem_urls.py --urls Problems/urls_contests.txt",
    "# Headers contain '/' so they become the record's source_topic.",
    "",
]


# ── shared helpers ───────────────────────────────────────────────────────────

def read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return default


def already_in_corpus(problem_id: str, platform: str) -> bool:
    return (CORPUS / platform / f"{problem_id}.json").exists()


def seed_urls() -> set[str]:
    if not SEED_FILE.exists():
        return set()
    return {ln.strip() for ln in SEED_FILE.read_text().splitlines() if ln.strip().startswith("http")}


def append_seed_block(title: str, urls: list[str]) -> int:
    """Append one contest block; returns how many URLs were actually added.
    Append-only by design: Problems/urls.txt has BEGIN/END GENERATED regions
    that update_problem_urls.py rewrites wholesale, so contests get their own
    file and can never be clobbered by a refresh."""
    if not urls:
        return 0
    existing = SEED_FILE.read_text() if SEED_FILE.exists() else "\n".join(SEED_HEADER)
    present = {ln.strip() for ln in existing.splitlines() if ln.strip().startswith("http")}
    fresh = [u for u in urls if u not in present]
    if not fresh:
        return 0
    block = [f"# {title}"] + fresh + [""]
    SEED_FILE.parent.mkdir(parents=True, exist_ok=True)
    SEED_FILE.write_text(existing.rstrip("\n") + "\n\n" + "\n".join(block))
    return len(fresh)


def parse_contest_url(raw: str) -> tuple[str, Any]:
    s = raw.strip().rstrip("/")
    m = re.search(r"leetcode\.com/contest/([a-z0-9-]+)", s, re.I)
    if m:
        return "leetcode", m.group(1)
    m = re.search(r"codeforces\.com/(?:contest|contests)/(\d+)", s, re.I)
    if m:
        return "codeforces", int(m.group(1))
    raise ValueError(f"unrecognised contest url: {raw}")


# ── LeetCode ─────────────────────────────────────────────────────────────────

LC_CONTEST_QUERY = (
    "query c($t: String!) { contest(titleSlug: $t) { title startTime "
    "questions { titleSlug title credit } } }"
)


def ingest_leetcode(slug: str, dry_run: bool) -> dict[str, int]:
    data = request_json(LEETCODE_GRAPHQL_URL, {"query": LC_CONTEST_QUERY, "variables": {"t": slug}})
    if data.get("errors"):
        raise RuntimeError(str(data["errors"])[:200])
    contest = (data.get("data") or {}).get("contest")
    if not contest:
        raise RuntimeError(f"no such contest: {slug}")

    title = contest.get("title") or slug
    print(f"\n{title}")
    staged_already = seed_urls()
    urls, stats = [], {"skipped_q1": 0, "present": 0, "new": 0}
    for q in contest.get("questions") or []:
        credit = q.get("credit")
        qslug = q.get("titleSlug")
        if not qslug:
            continue
        if credit == LC_SKIP_CREDIT:
            stats["skipped_q1"] += 1
            print(f"    skip  credit={credit}  {qslug}   (Q1 warm-up)")
            continue
        url = f"https://leetcode.com/problems/{qslug}/"
        if already_in_corpus(f"leetcode-{qslug}", "leetcode"):
            stats["present"] += 1
            print(f"    have  credit={credit}  {qslug}   (in the corpus)")
            continue
        if url in staged_already:
            stats["present"] += 1
            print(f"    have  credit={credit}  {qslug}   (already queued for annotation)")
            continue
        stats["new"] += 1
        print(f"    NEW   credit={credit}  {qslug}")
        urls.append(url)

    if not dry_run:
        append_seed_block(f"LeetCode / {title}", urls)
    return stats


# ── Codeforces ───────────────────────────────────────────────────────────────

def cf_contest_problems(contest_id: int) -> list[dict[str, Any]]:
    # Bare URL on purpose: the API rejects contest.standings for non-admins when
    # ANY extra parameter is present ("available only via anonymous GET requests
    # with no extra parameters").
    data = request_json(CF_STANDINGS.format(cid=contest_id))
    if data.get("status") != "OK":
        raise RuntimeError(f"codeforces api: {data.get('comment', 'failed')[:120]}")
    return (data.get("result") or {}).get("problems") or []


PAGE = 100


def row_to_entry(r: dict[str, Any]) -> tuple[str, dict[str, Any]] | None:
    cid, index = r.get("contest_id"), (r.get("index") or "")
    statement = (r.get("description") or "").strip()
    if not cid or not index or len(statement) < 80:
        return None
    key = f"codeforces-{cid}-{str(index).lower()}"
    return key, {
        "id": key,
        "contest_id": cid,
        "index": index,
        "title": r.get("title") or f"{cid}{index}",
        "rating": r.get("rating"),
        "tags": r.get("tags") or [],
        "statement": statement[:6000],
        "url": f"https://codeforces.com/problemset/problem/{cid}/{index}",
    }


def build_hf_index() -> dict[str, int]:
    """One full pass over the dataset recording key -> row offset.

    Paging all ~9,500 rows takes ~25 minutes and the datasets-server 502s on
    the odd page, which is fine once and intolerable weekly — and weekly is
    exactly the shape of `--retry-pending`. With this index, answering "has a
    statement appeared yet?" is a dict lookup, and fetching the ones that HAVE
    appeared touches only the pages holding them."""
    print("  building the open-r1 key index (one slow pass, cached for a week)…")
    index: dict[str, int] = {}
    total = int(request_json(HF_ROWS.format(offset=0, length=1)).get("num_rows_total") or 0)
    for offset in range(0, total, PAGE):
        try:
            data = request_json(HF_ROWS.format(offset=offset, length=PAGE))
        except Exception as exc:  # noqa: BLE001 — a flaky page must not abort the pass
            print(f"    page {offset} unreadable: {str(exc)[:60]}", file=sys.stderr)
            continue
        for i, entry in enumerate(data.get("rows", [])):
            got = row_to_entry(entry.get("row") or {})
            if got:
                index.setdefault(got[0], offset + i)
        if offset and offset % (PAGE * 20) == 0:
            print(f"    scanned {offset}/{total}, indexed {len(index)}")
    HF_INDEX.parent.mkdir(parents=True, exist_ok=True)
    HF_INDEX.write_text(json.dumps(
        {"fetched_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
         "rows": total, "keys": index}, indent=0) + "\n")
    print(f"  indexed {len(index)} problems")
    return index


def load_hf_index(force_refresh: bool = False) -> dict[str, int]:
    cached = read_json(HF_INDEX, None)
    if cached and not force_refresh:
        try:
            age = datetime.now(timezone.utc) - datetime.fromisoformat(cached["fetched_at"])
            if age.days < HF_INDEX_MAX_AGE_DAYS:
                return cached["keys"]
            print(f"  key index is {age.days} days old — refreshing")
        except (KeyError, ValueError):
            pass
    return build_hf_index()


def hf_lookup(wanted: set[str], force_refresh: bool = False) -> dict[str, dict[str, Any]]:
    """Resolve wanted `codeforces-<id>-<index>` keys to full rows, consulting
    the cached key index so an unavailable problem costs nothing."""
    if not wanted:
        return {}
    index = load_hf_index(force_refresh)
    hits = {k: index[k] for k in wanted if k in index}
    if not hits:
        return {}
    # Fetch only the pages that actually contain a wanted row.
    found: dict[str, dict[str, Any]] = {}
    for page_start in sorted({(off // PAGE) * PAGE for off in hits.values()}):
        try:
            data = request_json(HF_ROWS.format(offset=page_start, length=PAGE))
        except Exception as exc:  # noqa: BLE001
            print(f"    page {page_start} unreadable: {str(exc)[:60]}", file=sys.stderr)
            continue
        for entry in data.get("rows", []):
            got = row_to_entry(entry.get("row") or {})
            if got and got[0] in wanted:
                found[got[0]] = got[1]
    return found


def merge_statements(entries: dict[str, dict[str, Any]]) -> int:
    """MERGE, never overwrite. fetch_codeforces.py and fetch_codeforces_named.py
    both truncate this file; running either for a contest would wipe the cache
    every other ingest depends on."""
    if not entries:
        return 0
    cache = read_json(CF_STATEMENTS, {})
    before = len(cache)
    cache.update(entries)
    CF_STATEMENTS.parent.mkdir(parents=True, exist_ok=True)
    CF_STATEMENTS.write_text(json.dumps(cache, ensure_ascii=False, indent=1) + "\n")
    return len(cache) - before


def stage_codeforces(problems: list[dict[str, Any]], contest_id: int, label: str,
                     dry_run: bool) -> dict[str, int]:
    stats = {"present": 0, "staged": 0, "queued": 0}
    wanted, meta = set(), {}
    for p in problems:
        index = p.get("index") or ""
        key = f"codeforces-{contest_id}-{index.lower()}"
        if already_in_corpus(key, "codeforces"):
            stats["present"] += 1
            continue
        wanted.add(key)
        meta[key] = {"contest_id": contest_id, "index": index,
                     "name": p.get("name") or "", "tags": p.get("tags") or []}
    if not wanted:
        return stats

    found = hf_lookup(wanted)
    missing = sorted(wanted - set(found))
    stats["staged"] = len(found)
    stats["queued"] = len(missing)

    if not dry_run:
        merge_statements(found)
        append_seed_block(f"Codeforces / {label}",
                          [found[k]["url"] for k in sorted(found)])
        if missing:
            queue_pending([meta[k] | {"id": k} for k in missing])

    for k in sorted(found):
        print(f"    NEW   {k}  {found[k]['title'][:40]}")
    for k in missing:
        print(f"    queue {k}  {meta[k]['name'][:40]}   (no statement in the dataset yet)")
    return stats


# ── the pending queue ────────────────────────────────────────────────────────

def queue_pending(items: list[dict[str, Any]]) -> None:
    pend = read_json(PENDING, {"note": "Codeforces problems awaiting a statement in "
                                       "open-r1/codeforces. Retry: ingest_contest.py --retry-pending",
                               "problems": []})
    have = {p["id"] for p in pend["problems"]}
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    for it in items:
        if it["id"] in have:
            continue
        pend["problems"].append({**it, "first_seen": now})
    pend["count"] = len(pend["problems"])
    PENDING.write_text(json.dumps(pend, ensure_ascii=False, indent=1) + "\n")


def retry_pending(dry_run: bool) -> dict[str, int]:
    pend = read_json(PENDING, None)
    if not pend or not pend.get("problems"):
        print("nothing queued")
        return {"staged": 0, "still_waiting": 0}

    # A queued problem may have been ingested by some other path since.
    live = [p for p in pend["problems"] if not already_in_corpus(p["id"], "codeforces")]
    dropped = len(pend["problems"]) - len(live)
    print(f"{len(live)} queued problem(s) to re-check" + (f", {dropped} already ingested" if dropped else ""))

    # The statement cache first. fetch_statements.py (Tavily) fills it for
    # problems the dataset hasn't published yet, and a statement is a statement
    # whatever fetched it — checking here is what lets the two paths compose
    # instead of the Tavily one needing its own staging code.
    cached = read_json(CF_STATEMENTS, {})
    found = {p["id"]: cached[p["id"]] for p in live if p["id"] in cached}
    if found:
        print(f"  {len(found)} already in the statement cache")
    missing = {p["id"] for p in live if p["id"] not in found}
    found.update(hf_lookup(missing))
    if not dry_run:
        merge_statements(found)
        by_contest: dict[int, list[str]] = {}
        for key in sorted(found):
            by_contest.setdefault(found[key]["contest_id"], []).append(found[key]["url"])
        for cid, urls in by_contest.items():
            append_seed_block(f"Codeforces / Contest {cid}", urls)
        remaining = [p for p in live if p["id"] not in found]
        pend["problems"] = remaining
        pend["count"] = len(remaining)
        PENDING.write_text(json.dumps(pend, ensure_ascii=False, indent=1) + "\n")

    for key in sorted(found):
        print(f"    NEW   {key}  {found[key]['title'][:40]}")
    still = [p for p in live if p["id"] not in found]
    for p in still:
        print(f"    wait  {p['id']}  queued {p.get('first_seen', '?')}")
    return {"staged": len(found), "still_waiting": len(still)}


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("urls", nargs="*", help="contest URLs (leetcode.com/contest/... or codeforces.com/contest/N)")
    ap.add_argument("--retry-pending", action="store_true", help="re-check queued Codeforces problems")
    ap.add_argument("--dry-run", action="store_true", help="report what would be staged; write nothing")
    ap.add_argument("--refresh-index", action="store_true",
                    help="rebuild the open-r1 key index now instead of waiting for it to age out")
    args = ap.parse_args()

    if not args.urls and not args.retry_pending and not args.refresh_index:
        ap.error("give a contest URL, --retry-pending, or --refresh-index")

    totals = {"new": 0, "queued": 0}
    if args.refresh_index:
        build_hf_index()
    if args.retry_pending:
        out = retry_pending(args.dry_run)
        totals["new"] += out["staged"]
        totals["queued"] += out["still_waiting"]

    for raw in args.urls:
        try:
            judge, ident = parse_contest_url(raw)
        except ValueError as exc:
            print(f"  {exc}", file=sys.stderr)
            continue
        try:
            if judge == "leetcode":
                st = ingest_leetcode(ident, args.dry_run)
                totals["new"] += st["new"]
            else:
                print(f"\nCodeforces contest {ident}")
                probs = cf_contest_problems(ident)
                st = stage_codeforces(probs, ident, f"Contest {ident}", args.dry_run)
                totals["new"] += st["staged"]
                totals["queued"] += st["queued"]
        except Exception as exc:  # noqa: BLE001 — one bad contest shouldn't kill the rest
            print(f"  {raw}: {str(exc)[:160]}", file=sys.stderr)
        time.sleep(0.3)

    print(f"\n{totals['new']} problem(s) staged" +
          (f", {totals['queued']} waiting on a statement" if totals["queued"] else ""))
    if args.dry_run:
        print("(dry run — nothing written)")
        return 0
    if totals["new"]:
        print(f"""
next:
  python3 scripts/annotate_problem_urls.py --urls {SEED_FILE.relative_to(ROOT)} --platform leetcode --platform codeforces --model gpt-4.1
  python3 scripts/apply_source_tags.py --write        # judge tags -> taxonomy (LeetCode tags land days later)
  python3 scripts/backfill_acceptance_rate.py --write  # metadata only, no re-embed needed
  npm run embed && npm run validate                   # embed FIRST: validate checks corpusHash
  git diff --stat && git add -A && git commit && git push""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
