"""Brute-force check of the proposed solution to Kattis 'zoomanagement' (ICPC WF 2022 A).

Model: a move rotates the animals along a set of vertex-disjoint simple cycles of
length >= 3 (a 2-cycle would reuse the tunnel, which is forbidden).  Composing
moves, the reachable group is generated by single-cycle rotations.

Proposed rule (see solution notes):
  * animals can never cross a bridge, so decompose into bridgeless components;
  * a singleton bridgeless component must already hold its target animal;
  * a component that is exactly one simple cycle: the reachable arrangements are
    the L rotations -> cyclic-rotation match of the b-sequence against e;
  * any other bridgeless component (2-edge-connected, not a cycle): the group is
    A_N, and it is S_N iff the component contains an even cycle (equivalently:
    some block is not an odd cycle).  So multiset equality suffices, except in
    the all-odd-blocks case where, when every colour in the component is
    distinct, the induced permutation must be even.

The script (1) BFS's the true reachable set of arrangements on small graphs and
compares with the rule, and (2) identifies the generated group itself.
"""
import itertools, random
from collections import deque

# ---------------------------------------------------------------- brute force
def simple_cycles(n, adj):
    """All simple cycles (length>=3) as vertex tuples, each once."""
    out = []
    for start in range(n):
        # paths whose minimum vertex is `start`
        stack = [(start, [start], {start})]
        while stack:
            v, path, seen = stack.pop()
            for w in adj[v]:
                if w == start and len(path) >= 3:
                    if path[1] < path[-1]:          # canonical direction
                        out.append(tuple(path))
                elif w > start and w not in seen:
                    stack.append((w, path + [w], seen | {w}))
    return out

def reachable_set(n, cycles, start):
    """BFS over colourings; a generator rotates one cycle by one step."""
    seen = {start}
    dq = deque([start])
    while dq:
        cur = dq.popleft()
        for cyc in cycles:
            for d in (1, -1):
                nxt = list(cur)
                k = len(cyc)
                for i, v in enumerate(cyc):
                    nxt[cyc[(i + d) % k]] = cur[v]
                nxt = tuple(nxt)
                if nxt not in seen:
                    seen.add(nxt)
                    dq.append(nxt)
    return seen

# ------------------------------------------------------------------- the rule
def bridges(n, edges):
    adj = [[] for _ in range(n)]
    for i, (u, v) in enumerate(edges):
        adj[u].append((v, i)); adj[v].append((u, i))
    tin = [-1]*n; low = [0]*n; timer = [0]; br = set()
    def dfs(v, pe):
        tin[v] = low[v] = timer[0]; timer[0] += 1
        for (w, ei) in adj[v]:
            if ei == pe: continue
            if tin[w] != -1:
                low[v] = min(low[v], tin[w])
            else:
                dfs(w, ei)
                low[v] = min(low[v], low[w])
                if low[w] > tin[v]: br.add(ei)
    for v in range(n):
        if tin[v] == -1: dfs(v, -1)
    return br

class DSU:
    def __init__(s, n): s.p = list(range(n))
    def f(s, x):
        while s.p[x] != x: s.p[x] = s.p[s.p[x]]; x = s.p[x]
        return x
    def u(s, a, b): s.p[s.f(a)] = s.f(b)

def blocks(n, edges):
    """Biconnected components as lists of edge indices."""
    adj = [[] for _ in range(n)]
    for i, (u, v) in enumerate(edges):
        adj[u].append((v, i)); adj[v].append((u, i))
    tin = [-1]*n; low = [0]*n; timer = [0]; st = []; out = []
    def dfs(v, pe):
        tin[v] = low[v] = timer[0]; timer[0] += 1
        for (w, ei) in adj[v]:
            if ei == pe: continue
            if tin[w] != -1:
                if tin[w] < tin[v]: st.append(ei); low[v] = min(low[v], tin[w])
            else:
                st.append(ei); dfs(w, ei); low[v] = min(low[v], low[w])
                if low[w] >= tin[v]:
                    comp = []
                    while True:
                        e = st.pop(); comp.append(e)
                        if e == ei: break
                    out.append(comp)
    for v in range(n):
        if tin[v] == -1: dfs(v, -1)
    return out

def perm_parity(p):
    seen = [False]*len(p); par = 0
    for i in range(len(p)):
        if not seen[i]:
            j = i; ln = 0
            while not seen[j]: seen[j] = True; j = p[j]; ln += 1
            par ^= (ln - 1) & 1
    return par            # 0 = even

def cyclic_match(bs, es):
    L = len(bs)
    for r in range(L):
        if all(bs[i] == es[(i + r) % L] for i in range(L)):
            return True
    return False

def solve(n, edges, b, e):
    br = bridges(n, edges)
    d = DSU(n)
    for i, (u, v) in enumerate(edges):
        if i not in br: d.u(u, v)
    comps = {}
    for v in range(n): comps.setdefault(d.f(v), []).append(v)
    blk = blocks(n, edges)
    blk_of_root = {}
    for comp in blk:
        if len(comp) == 1 and comp[0] in br: continue
        r = d.f(edges[comp[0]][0])
        blk_of_root.setdefault(r, []).append(comp)
    for root, vs in comps.items():
        N = len(vs)
        if N == 1:
            if b[vs[0]] != e[vs[0]]: return False
            continue
        if sorted(b[v] for v in vs) != sorted(e[v] for v in vs): return False
        cedges = [i for i, (u, v) in enumerate(edges) if i not in br and d.f(u) == root]
        deg = {v: 0 for v in vs}
        for i in cedges: deg[edges[i][0]] += 1; deg[edges[i][1]] += 1
        is_cycle = (len(cedges) == N and all(deg[v] == 2 for v in vs))
        if is_cycle:
            # walk the cycle
            adj = {v: [] for v in vs}
            for i in cedges: adj[edges[i][0]].append(edges[i][1]); adj[edges[i][1]].append(edges[i][0])
            order = [vs[0]]; prev = None; cur = vs[0]
            while len(order) < N:
                nxt = [w for w in adj[cur] if w != prev][0]
                order.append(nxt); prev, cur = cur, nxt
            if not cyclic_match([b[v] for v in order], [e[v] for v in order]): return False
            continue
        # non-cycle 2-edge-connected component
        has_even_cycle = False
        for comp in blk_of_root.get(root, []):
            vset = set()
            for i in comp: vset |= {edges[i][0], edges[i][1]}
            if not (len(comp) == len(vset) and len(vset) % 2 == 1):
                has_even_cycle = True; break
        if has_even_cycle: continue                     # S_N
        vals = [b[v] for v in vs]
        if len(set(vals)) < N: continue                 # repeated colour -> both parities
        # unique permutation: animal at position i must land where e wants it
        pos = {e[v]: v for v in vs}
        idx = {v: k for k, v in enumerate(vs)}
        p = [idx[pos[b[v]]] for v in vs]
        if perm_parity(p) != 0: return False
    return True

# ------------------------------------------------------------------ the tests
def all_connected_graphs(n):
    pairs = list(itertools.combinations(range(n), 2))
    for mask in range(1 << len(pairs)):
        edges = [pairs[i] for i in range(len(pairs)) if mask >> i & 1]
        d = DSU(n)
        for u, v in edges: d.u(u, v)
        if len({d.f(v) for v in range(n)}) == 1:
            yield edges

def group_name(n, cycles):
    ident = tuple(range(n))
    reach = reachable_set(n, cycles, ident)
    import math
    f = math.factorial(n)
    if len(reach) == f: return "S"
    if len(reach) == f // 2: return "A"
    return "|%d|" % len(reach)

def run(n, graphs, trials, colour_pool, label):
    bad = 0
    for edges in graphs:
        adj = [[] for _ in range(n)]
        for u, v in edges: adj[u].append(v); adj[v].append(u)
        cycles = simple_cycles(n, adj)
        for _ in range(trials):
            b = [random.choice(colour_pool) for _ in range(n)]
            e = b[:]; random.shuffle(e)
            truth = tuple(e) in reachable_set(n, cycles, tuple(b))
            got = solve(n, edges, b, e)
            if truth != got:
                bad += 1
                if bad <= 5:
                    print("MISMATCH", label, "edges", edges, "b", b, "e", e, "truth", truth, "rule", got)
    print(f"{label}: n={n}, graphs={len(graphs)}, mismatches={bad}")
    return bad

if __name__ == "__main__":
    random.seed(11)

    # 0. samples from the statement
    samples = [
        (3, [(0,1),(1,2),(0,2)], [1,4,7], [4,7,1], True),
        (2, [(0,1)], [1,2], [2,1], False),
        (5, [(0,1),(1,2),(0,2),(2,3),(2,4),(3,4)], [10,20,30,40,50], [40,30,50,20,10], True),
        (4, [(0,1),(1,2),(2,3),(0,3)], [10,10,20,20], [10,20,10,20], False),
    ]
    for i, (n, E, b, e, want) in enumerate(samples, 1):
        got = solve(n, E, b, e)
        print(f"sample {i}: rule={'possible' if got else 'impossible'} expected={'possible' if want else 'impossible'} {'OK' if got==want else 'FAIL'}")

    # 1. which group does each connected graph generate?
    print("\n-- generated group for every connected graph on 4 and 5 vertices --")
    seen_kinds = {}
    for n in (4, 5):
        for edges in all_connected_graphs(n):
            adj = [[] for _ in range(n)]
            for u, v in edges: adj[u].append(v); adj[v].append(u)
            cycles = simple_cycles(n, adj)
            br = bridges(n, edges)
            bridgeless = [i for i in range(len(edges)) if i not in br]
            nm = group_name(n, cycles)
            # classify graph: cycle / has bridge / 2ec-noncycle-odd / 2ec-noncycle-even
            if len(bridgeless) == 0: kind = "forest"
            elif len(br) > 0: kind = "has bridge"
            elif len(edges) == n: kind = "single cycle"
            else:
                ev = any(len(c) % 2 == 0 for c in cycles)
                kind = "2ec non-cycle, even cycle" if ev else "2ec non-cycle, all odd"
            seen_kinds.setdefault((n, kind), set()).add(nm)
    for k in sorted(seen_kinds): print("   ", k, "->", sorted(seen_kinds[k]))

    # 2. full reachability cross-check
    print()
    tot = 0
    for n in (3, 4, 5):
        gs = list(all_connected_graphs(n))
        tot += run(n, gs, 6, list(range(1, n + 1)), "distinct-ish colours")
        tot += run(n, gs, 6, [1, 2], "two colours")
        tot += run(n, gs, 4, [1, 1, 2, 3], "duplicates")
    # n=6, sampled graphs (BFS over 720 perms is fine)
    n = 6
    pairs = list(itertools.combinations(range(n), 2))
    gs = []
    while len(gs) < 120:
        edges = [p for p in pairs if random.random() < random.choice([0.3, 0.4, 0.55])]
        d = DSU(n)
        for u, v in edges: d.u(u, v)
        if len({d.f(v) for v in range(n)}) == 1: gs.append(edges)
    tot += run(n, gs, 4, list(range(1, 7)), "n=6 distinct")
    tot += run(n, gs, 4, [1, 2, 3], "n=6 repeats")
    print("\nTOTAL MISMATCHES:", tot)

# --------------------------------------------------- targeted structural tests
def targeted():
    random.seed(7)
    tests = []
    # chains / stars of odd cycles glued at cut vertices (all-odd blocks -> A_N)
    tests.append((7, [(0,1),(1,2),(0,2),(2,3),(3,4),(2,4),(4,5),(5,6),(4,6)]))   # 3 triangles chained
    tests.append((7, [(0,1),(1,2),(0,2),(0,3),(3,4),(0,4),(0,5),(5,6),(0,6)]))   # 3 triangles at one hub
    tests.append((7, [(0,1),(1,2),(2,3),(3,4),(0,4),(4,5),(5,6),(4,6)]))         # C5 + triangle
    tests.append((7, [(0,1),(1,2),(2,3),(3,4),(0,4),(4,5),(5,6),(6,0)]))         # C5 + C4 sharing v0,v4? (2-conn)
    # odd cycle + bridge + odd cycle (animals must stay put across the bridge)
    tests.append((7, [(0,1),(1,2),(0,2),(2,3),(3,4),(4,5),(3,5),(5,6)]))
    # disconnected: triangle + C4 + isolated vertex
    tests.append((8, [(0,1),(1,2),(0,2),(3,4),(4,5),(5,6),(3,6)]))
    # theta graphs (2-connected, non-cycle)
    tests.append((6, [(0,1),(1,2),(2,5),(0,3),(3,5),(0,4),(4,5)]))
    tests.append((7, [(0,1),(1,2),(2,3),(3,6),(0,4),(4,6),(0,5),(5,6)]))
    bad = 0
    for n, edges in tests:
        adj = [[] for _ in range(n)]
        for u, v in edges: adj[u].append(v); adj[v].append(u)
        cycles = simple_cycles(n, adj)
        for pool in (list(range(1, n + 1)), [1, 2, 3], [1, 1, 2, 2, 3, 3, 4, 4]):
            for _ in range(40):
                b = [random.choice(pool) for _ in range(n)]
                e = b[:]; random.shuffle(e)
                truth = tuple(e) in reachable_set(n, cycles, tuple(b))
                got = solve(n, edges, b, e)
                if truth != got:
                    bad += 1
                    if bad <= 5: print("MISMATCH targeted", n, edges, b, e, truth, got)
    print("targeted structural tests: mismatches =", bad)
    return bad

if __name__ == "__main__":
    print()
    targeted()
